### ISSUE TITLE
Create automated PR

### ISSUE THREAD

**Issue by tubamos** [amosproj/amos2024ss06-health-ai-framework#103]
### Item type: Environment and Tooling

**Description:** Create a Github actions automation that will generate a Pull Request with the name `issue-{NUMBER}` linked to the issue of the respective number.

**Comment by tubamos** [comment]
Also, @preetvadaliya, this is more a formality than an actuall need of course, but could you please estiamte this task yourself so that we have a base for the review?

**Comment by preetvadaliya** [comment]
@tubamos no need to add anytime here, it was just few line code. I have linked the PR that also contains version bump of dependent action. and i have also created a small CI if you want to create branch from issue just comment `/cib` that will create branch and show you checkout instructions

**Comment by tubamos** [comment]
Great, thanks Preet! 🙌
