### ISSUE TITLE
Implement the LangChain pipeline in Typescript

### ISSUE THREAD

**Issue by tubamos** [amosproj/amos2024ss06-health-ai-framework#118]
# Item type: data pipeline

**Description:** As people have figured out lately, it is possible to convert the LangChain pipeline in TypeScript so that it can be integrated directly into the frontend of the mobile app without the need for a backend server. 

I am not sure how a full decoupling from a backend can be achieved (e.g. how the API keys can be protected in this way). 

This can probably be done by utilising the LangChain.js version of LangChain.

https://js.langchain.com/v0.2/docs/introduction/

https://github.com/langchain-ai/langchainjs

![Image](https://github.com/amosproj/amos2024ss06-health-ai-framework/assets/166435676/315d2d62-7f54-4b73-8b20-2a8c4548092f)

# User story
- As a developer of this team, 
- I want to rewrite the LangChain pipeline in TypeScript so that it can integrate directly with the mobile app frontend, 
- eliminating the need for backend infrastructure.

# Acceptance Criteria
- [x] The LangChain pipeline has been fully implemented in TypeScript
- [x] No keys to other services (OpenAI etc.) have been embeded in the code

# Definition of Done
- [ ] The feature has been fully implemented.
- [ ] The feature has been manually tested and works as expected without critical bugs.
- [ ] The feature code is documented with clear explanations of its functionality and usage.
- [ ] The feature code has been reviewed and approved by at least one team member.
- [ ] The feature branches have been merged into the main branch and closed.

**Comment by preetvadaliya** [comment]
> No keys to other services (OpenAI etc.) have been embedded in the code.

@tubamos , We need keys to call but that will be inside `.env` file so it will be not visible on GitHub, and only used while build process.

Even someone try to de-compile android or iOS app then it will be converted into garbage during to de-compile process, so no one get it.

**Comment by preetvadaliya** [comment]
@tubamos , Here I am seeing LangSmith that will be a good approach to debug app because we will be able to see user's query selected documents from vectorDB and response generated by OpenAI. If someone like to explore this then it might be helpful in future.

**Comment by preetvadaliya** [comment]
> The feature has been fully implemented and integrated into the app.

This thing is depends upon the development of other mobile app stuffs like Auth and etc, so I suggest if someone can show a raw JS or TS that print results on console then also we can consider it as completed. then it will be easy to attach it with app in future.
