### ISSUE TITLE
Setup user authentication

### ISSUE THREAD

**Issue by tubamos** [amosproj/amos2024ss06-health-ai-framework#119]
### Item type: App backend
**Description:** The authentication functionality should allow user to set-up account, register with email/username and password and later be able to login using their credentials. This functionality should give an option to login using multiple methods such as social login. Firebase is ideal for this functionality as it offers fast, safe and scalable services integrated with databases. 

### User story

- As a owner of this solution
- I need to have the user authentication functionality implemented
- so that a user can register, login and authenticate themselves to use the service

### Acceptance Criteria
- [x] The Firebase authenticator has been configured to support multiple methods
  - [x] Google Account Sign-in
  - [x] Email
- [x] The authentication methods have been implemented and tested.
- [x] A user can login into the app and receive a temporary confirmation text for the fact in the screen of the empty app.

### Definition of Done
- [ ] The feature has been fully implemented.
- [ ] The feature has been manually tested and works as expected without critical bugs.
- [ ] The feature code is documented with clear explanations of its functionality and usage.
- [ ] The feature code has been reviewed and approved by at least one team member.
- [ ] The feature branches have been merged into the main branch and closed.

**Comment by preetvadaliya** [comment]
@tubamos , @Ghemechis 

Its look good no need any comment but yeh, Signup process with email and password will be easy not that hard, but for Google SignUp flow we need some extra config both side.

1. Firebase side: congif app with firebase and get service json for android and ios and add in project.
2. Expo App side: add paths of service file in `app.json` and also we will have to build developer build so native module will be added for auth(Google SignIn need that).

**Comment by preetvadaliya** [comment]
Also we have to handle keystore which is sha256 key to identify the App and firebase.
