### ISSUE TITLE
Orchestrator: automatically create data/ folder and config.json

### ISSUE THREAD

**Issue by tubamos** [amosproj/amos2024ss06-health-ai-framework#123]
# Acceptance criteria

As formulated by Eloi:
- [ ] The config/orchestrator automatically creates the `data/` folder and the `config.json` if they do not exist 
- [ ] The config/orchestrator does not throw errors anymore (as it does now) in these cases.

**Comment by eloinoel** [comment]
Discovered that Preet already did this at the beginning of this sprint.
