### ISSUE TITLE
Create components for basic visual navigation

### ISSUE THREAD

**Issue by tubamos** [amosproj/amos2024ss06-health-ai-framework#153]
# Domain:
App frontend

# Description
Implement the foundational navigation system for the app using React Native. The components should allow users to switch between the main screens, such as login, chat, and profile, with ease. There is manu icon (or similar) a navigation bar (or similar) some basic transitions, some account icon, a logout icon etc. 

Here is the link to the UX/UI screens:
https://www.figma.com/design/gwKyWFjAkDJpnwlYOLqaH5/Frontend-Wireframe?node-id=0-1

![Image](https://github.com/amosproj/amos2024ss06-health-ai-framework/assets/166435676/04fd96a4-80ea-4b83-8be4-85e176318f3a)

The image above is just one example of how navigation could be implemented.

The UX/UI guidelines of android which we are targeting at the moment indicate the ways that navigation can be implemented using various concepts for various screen sizes such as a "navigation rail", "navigation bar" or "navigation drawer". We focus on the navigation bar (for mibile screens) at the moment if the overhead in buidling the whole system is too much.

For more details please check this out:
https://m3.material.io/foundations/layout/understanding-layout/parts-of-layout

These are more or less components that can be easily found ready made and just need to be configured, integrated (in a cohesive way to the visual and UX conventions of our app) and made to work in our context.

# User Story
- As a user, 
- I want a reliable navigation system 
- so that I can switch between different sections of the app

# Acceptance Criteria
- [ ] Navigation framework is set up.
- [ ] Icons for user logout and user settings are present.
- [ ] The user can navigate between the login screen to the chat screen in some way (press of a button in a navigation bar or similar)
- [ ] Similarly, users can navigate from the chat screen to the profile screen.
- [ ] Navigation menus are self-understood based on current conventions and responsive.
- [ ] Back navigation works correctly on all screens.

# Definition of Done
- [ ] The feature has been fully implemented.
- [ ] The feature has been manually tested and works as expected without critical bugs.
- [ ] The feature code is documented with clear explanations of its functionality and usage.
- [ ] The feature code has been reviewed and approved by at least one team member.
- [ ] The feature branches have been merged into the main branch and closed.

**Comment by lukas-varga** [comment]
![Image](https://github.com/amosproj/amos2024ss06-health-ai-framework/assets/72818751/aa786f05-5732-4ee8-a336-e81584673518)
