### ISSUE TITLE
Create components for the chat screen

### ISSUE THREAD

**Issue by tubamos** [amosproj/amos2024ss06-health-ai-framework#154]
# Domain
App frontend

# Description
Implement the chat screen components using React Native. This includes creating a dynamic chat interface where users can input questions and view responses from agents. The interface should include the typical elements of a chat interface such as an input field, a send button and chat bubbles for displaying the conversation which get updated in real time (there are several libraries for chat UI components and firebase can probably handle most of the chatting logic).

To be taken by a pair.

The screens that are related to this task from the UX/UI plan that we have so far are the two pasted below. This does not mean though that you have to implement them exact;y as they look there. As long as the core functionality has been implemented in a robust way feel free to coordinate the use of a common ui library ith the rest of the team the builds compoents so that the aesthetic aspect of the app is consistent right from the start.

![Image](https://github.com/amosproj/amos2024ss06-health-ai-framework/assets/166435676/e0862ffc-4a85-460c-b7f0-2b256bc6ae2e)

Here is the link to the UX/UI screens:
https://www.figma.com/design/gwKyWFjAkDJpnwlYOLqaH5/Frontend-Wireframe?node-id=0-1

There is a plethora of resources with ready made compoents for these type of screens thet we could use. Just to list a few:
- https://mui.com/
- https://rn-material.js.org/
- https://reactnativepaper.com/
- https://reactnativeelements.com/

The task assumes that the devs will communicate before building anything in order to select a library that has all the necessary components for the app in general (not only during this sprint) so that waht we will create in the end is cohesive as a whole and consistend visually.

# User Story
- As a user, 
- I want to interact with the agent through a chat interface 
- so that I can get answers to my questions.

# Acceptance Criteria
- [ ] Users can type messages in a designated input field.
- [ ] When a use presses the send button the sent message is directly displayed at the screen alongside the previous messages.
- [ ] While the user waits for the answer there is some form of activity indicator that informs the user that the system is working in the background to generate the response.
- [ ] The chat interface displays messages in a clear, organized manner.
- [ ] Some form of visual styling distinguishes the user messages from the agent responses.
- [ ] The chat updates in real-time without noticeable delay.

# Definition of Done
- [ ] The feature has been fully implemented.
- [ ] The feature has been manually tested and works as expected without critical bugs.
- [ ] The feature code is documented with clear explanations of its functionality and usage.
- [ ] The feature code has been reviewed and approved by at least one team member.
- [ ] The feature branches have been merged into the main branch and closed.

**Comment by lukas-varga** [comment]
![Image](https://github.com/amosproj/amos2024ss06-health-ai-framework/assets/72818751/536bd4a6-2c56-4c51-95e5-34f944a08264)
