### ISSUE TITLE
Present recent conversations

### ISSUE THREAD

**Issue by Ghemechis** [amosproj/amos2024ss06-health-ai-framework#172]
# Dependencies

- #176 

---

### Item type: App, Frontend, backend

**Description** : The conversation history feature allows users to view their recent chat history by retrieving it from the database (implemented on #176 ). Conversations are organized by the chat subject as the title. When a specific chat title is selected, the detailed conversation between the user and the AI should be displayed. This functionality is accessed through the "Recent Conversations" button located just below the search bar on the UI. When this button is selected, the titles of recent conversations should be displayed

### User Story
As a user of AI chat app,
I want to view my recent chat history by retrieving it from the database,
so that I can easily access and review my past interactions with the AI agent.

### Acceptance criteria
[ ]  removed previously implemented multiple domain functionality (e.g. MedicineBOt, ChessBot, CarBot)
[ ] Added "Recent conversations" button or tab to the UI interface.
[ ]  Implemented a view that displays a list of conversation titles in chronological order when the "Recent conversations" button is clicked.
[ ]  When a title is clicked, expand to show the chat interactions including timestamp, username, and message.

### Definition of done
[ ]   The feature has been fully implemented.
[ ]   The feature has been manually tested and works as expected without critical bugs.
[ ]   The feature code is documented with clear explanations of its functionality and usage.
[ ]   The feature code has been reviewed and approved by at least one team member.
[ ]   The feature branches have been merged into the main branch and closed.
[ ]   The feature utility, function and usage have been documented in the respective project wiki on github.

**Comment by preetvadaliya** [comment]
Same comment as #175 but for all chats so again new one hooks `useGetAllChat` we dont need `useUpdateAllChat` bcz we dont have any operation in which we need to do so.
