### ISSUE TITLE
Present references in agent answers

### ISSUE THREAD

**Issue by tubamos** [amosproj/amos2024ss06-health-ai-framework#174]
# Domain
app frontend

# Description
Develop the react native components that will list the references for each agent's response. These components will allow users to see and visit the origin of the information that was used to produce the answer making the answers verifiable and more trustworthy.

# Example
Bing copilot has a good implementation of this feature.

### Bing's implementation:
![Image](https://github.com/amosproj/amos2024ss06-health-ai-framework/assets/166435676/af918243-a8f9-497d-b4d5-8cfff914586a)

### Wikipedia mobile implementation:
![Image](https://github.com/amosproj/amos2024ss06-health-ai-framework/assets/166435676/30ca02d9-d5fd-49e2-b2ed-e77dd98bbe37)

# User Story
- As a user, 
- I want to see the references for each agent's response, 
- so that I can verify the accuracy, credibility of the information provided and assess it's reliability.

# Acceptance Criteria
- [x] React native components to display a list of references for each agent's response have been created.
- [ ] Each reference presents: 
  - [ ] the source name
  - [x] the title 
  - [x] a hyperlink
- [x] The presented references are the correct ones.
- [x] References are clearly linked to the corresponding parts of the answer.
- [x] Users clicking on references can view detailed information or navigate to the source (e.g. in a browser).

# Definition of Done
- [ ] The feature has been fully implemented.
- [ ] The feature has been manually tested and works as expected without critical bugs.
- [ ] The feature code is documented with clear explanations of its functionality and usage.
- [ ] The feature code has been reviewed and approved by at least one team member.
- [ ] The feature branches have been merged into the main branch and closed.
- [ ] The feature utility, function and usage have been documented in the respective project wiki on github.

**Comment by preetvadaliya** [comment]
@tubamos ,

So far I know only one lib `react-native-gifted-chat` to handle chat UI and mostly people are using that.

We have already added a chat interface in our last sprint but I can't see a way that can handle this kind of logic because that is `<TEXT/>` elements aligned based on `sent` boolean value. probably we have to remove that during sprint.
