### ISSUE TITLE
Save conversations in the DB

### ISSUE THREAD

**Issue by tubamos** [amosproj/amos2024ss06-health-ai-framework#176]
### Item type: App, Frontend, backend

**Description** : This feature stores conversations between the user and the AI agent in the Firestore database, linking them to the user's unique ID on Firebase. Each saved conversation is organized by date and chat subject as the title, and includes the timestamp, username, and message in the body. This organization facilitates the retrieval of chat history in the UI later on. 

### User Story
As a user the AI agent app,
I want my conversations with the AI agent to be saved and organized in the Firestore database,
so that I can easily access my chat history later through the UI.

### Acceptance criteria
[ ]  The system shall store each conversation between the user and the AI agent in the Firestore database.
[ ]  Each stored conversation shall be linked to the user's unique ID on Firebase.
[ ]  Conversations shall be organized by date and have the chat subject as the title.
[ ] Each conversation entry shall include the timestamp, username, and message in the body.

### Definition of done
[ ]   The feature has been fully implemented.
[ ]   The feature has been manually tested and works as expected without critical bugs.
[ ]   The feature code is documented with clear explanations of its functionality and usage.
[ ]   The feature code has been reviewed and approved by at least one team member.
[ ]   The feature branches have been merged into the main branch and closed.
[ ]   The feature utility, function and usage have been documented in the respective project wiki on github.

**Comment by preetvadaliya** [comment]
Same comment as #175
