### ISSUE TITLE
Create option to change LLM

### ISSUE THREAD

**Issue by tubamos** [amosproj/amos2024ss06-health-ai-framework#177]
# Dependencies
- #175 

# Domain
app backend, data pipeline, app frontend

# Description
Implement backend functionality to support changing from GPT to Gemini and vice versa through a dropdown menu. This involves updating the LangChain pipeline to handle the switch dynamically based on user selection, ensuring the transition  takes place without hickups.

Add backend support for changing the underlying LLM. Initially we want to toggle between GPT and Gemini via the dropdown menu that has already been implemented in backlog item #175. 
To achieve this the LangChain pipeline needs to be updated so that it recognizes and applies the user-selected LLM for query processing.

# User Story
As a user, 
I want to dynamically change the underlying LLM of the agent from a dropdown menu, from GPT to Gemini and vice versa,
so that I can compare answers generated by different models like GPT and Gemini.

# Acceptance Criteria

- [ ] The LangChain pipeline has been modified / enhanced to support multiple LLM integrations.
- [ ] The model toggle is achieved by the UI components that are part of the dropdown component #175 
- When the underslying model changes, the dynamic display of the model name and version located at the top of the dropdown, change to reflect the current selection of the user.
- [ ] The developer has manually tested (as a user) and confirmed the successful dynamic change of the underslying LLM.

# Definition of Done
- [ ] The feature has been fully implemented.
- [ ] The feature has been manually tested and works as expected without critical bugs.
- [ ] The feature code is documented with clear explanations of its functionality and usage.
- [ ] The feature code has been reviewed and approved by at least one team member.
- [ ] The feature branches have been merged into the main branch and closed.
- [ ] The feature utility, function and usage have been documented in the respective project wiki on github.

**Comment by preetvadaliya** [comment]
@tubamos ,

We can use any LLM from this docs https://python.langchain.com/v0.2/docs/integrations/llms/

**Note:**
1. LLM should not need hosting.
2. Most of them can be connect using API keys.
