### ISSUE TITLE
Migrate the podcast transcription and data storage pipeline in GC

### ISSUE THREAD

**Issue by tubamos** [amosproj/amos2024ss06-health-ai-framework#28]
## Item type: Feature request

**Description**: Migrate the established data retrieval and storage pipeline for podcasts to the GC and complete the data retrieval, transcription and storage of all the episodes of the podcasts that are included in the sources spreadsheet:
https://docs.google.com/spreadsheets/d/1yq9mRF1P-1DX1i4nd-avEPkFQBNBTNt8-AYm-IrnZk4/edit#gid=309090183

## User story
1. As an industry partner / developer-entrepreneur
2. I need to have access text data from selected sources
3. so that I can later used them for context generation

## Acceptance criteria
* The the established data retrieval and storage pipeline for podcasts has been migrated to GC.
* The transcript data of all the episoeds and podcasts that are included in the sources spreadsheet have been retrieved and are stored within the DB in GC in a way that are accessible by all team members.

**Comment by tubamos** [comment]
@lukas-varga Will we need such a step now that we will work with Google Storage, so does this item need to be converted to be relative for GC instead of the HPC?

**Comment by lukas-varga** [comment]
> @lukas-varga, @preetvadaliya Will we need such a step now that we will work with Google Storage, so does this item need to be converted to be relative for GC instead of the HPC?

Yeah I guess so converting to GC makes sense.

**Comment by lukas-varga** [comment]
> @lukas-varga, 
> @preetvadaliya 
> 
> Guys, after the refactorings of last week in the orhestrator etc, are we still in need of such a step here? 
> Should I delete it entirely or it is still somehow relevant and it still has some value even with some alterations? If so what would the alterations need to be?

As far as I understand Preet has finished fully working HPC and GC, where we can deploy our project, so this task seems redundant to me.
