### ISSUE TITLE
Extract transcript from a single YouTube video locally

### ISSUE THREAD

**Issue by tubamos** [amosproj/amos2024ss06-health-ai-framework#5]
## Item type: Feature request

**Description**: Familiarize with YouTube API requirements for transcript extraction and storage and build a flexible pipeline for saving that data of one youtube video locally.

## User story
1. As an industry partner
2. I need to have access to youtube transcripted text data from particular channels
3. so that I can save the data in a datastore to later be used for model training

## Acceptance criteria
* The transcript data of one single video of one channel from those provided in the input list have been stored localy.
* The metadata (content of the description) of the same video have also been downlaoded and stored localy.

**Comment by manikg08** [comment]
The transcript from a single YouTube video has been downloaded and saved as a JSON file locally on our machine. A separate JSON file for the video IDs of all the YouTube videos on this channel has been generated. There are total 224 video Ids on this channel "https://www.youtube.com/@DrWilliamLi" .
A follow up story needs to be written to have further implementations of this code to all other channels.

**Comment by tubamos** [comment]
@manikg08 I think this is covered in: https://github.com/orgs/amosproj/projects/53/views/2?pane=issue&itemId=61243073

**Comment by manikg08** [comment]
Okay thanks for the info.
