### ISSUE TITLE
(documentation) Create build process video

### ISSUE THREAD

**Issue by tubamos** [amosproj/amos2024ss06-health-ai-framework#98]
# Item type: AMOS formal requirements

## Description as provided by the official documentation:

> - Create [build process video](https://docs.google.com/document/d/14xj_KeAx0tCbh7b4SJmDOY8tlpWwSrZO_i_XRDVOtk0/edit#heading=h.xgttzgekcivp) and upload to Deliverables folder
> - Consider using OBS Studio for creating the video
> - Name and upload file to sprint-05/build-process-video.mkv 
> - Or use other common container/codecs
> 
> 
> ### Build process video
> 
> The build process video demonstrates that you mastered the build process. 
> Typically, the video will show your terminal window.
> - Please narrate over the video to explain what you are doing
> - You can stop the process while explaining and continue thereafter.
> The build process consists of four main and one optional step:
> - Clone (the repository to start with a clean slate)
> - Build (the product from the clean repo)
> - Test (the product using automated test suites)
> - Optional: Deploy (to production environment)
> - Run (the product to show it starts up)
> 
> The most common scenario is to git clone and then build, test, deploy, and run using your build tool. If you have a fully automated CI process using GitHub, please trigger and show that.
> 
> If some steps cannot be automated, please carry them out by hand; you may want to copy over the commands from a separate text file to make things run smoothly.

---

## Comments from the Professor sent via email:

> Some projects don’t have to show much for a build process video, I guess. If you have no deployment model but run some Python code from the command line, there is nothing to show. (Running the Python code, like for data extraction, is not the build process, it is the application running.) Maybe you should containerize things. If there is nothing to show then maybe show your extraction code or training code but understand this is not the build process and comment accordingly. But again, I want to see the build process, not the application, in the upcoming deliverable.
> 
> If you have long running tasks that you can’t show in a single short session like for the mid-project review, then just create different environments (VMs if necessary) and stop them in different stages so that you can start a process for demo purposes in VM A and switch to VM B where it already finished. Or something like this. Be smart. You can also put this in a video.

# User Story 
As a member of this team 
I need to fulfill the formal module requirements
so that I can successfully progress in the next steps of the AMOS module without problems

# Acceptance Criteria
- [ ] A concept / script / list of steps has been created that describes the build process components and steps. 
- [ ] The contents and structure of the video match the requirements listed in the description of the official documentation (provided above)
- [ ] The screencapture video has been produced and (if needed) edited.
- [ ] The video had been renamed and upladed in the respective documentation directory.

**Comment by tubamos** [comment]
@lukas-varga 
@eloinoel 

Guys, you might want to create and connect a branch for this task because we will need to submit it anyway (if I am not mistaken in the docuementation directory) so it might as well be done like that.

**Comment by lukas-varga** [comment]
Okay let's do it like that.

**Comment by lukas-varga** [comment]
> @lukas-varga 
> @eloinoel 
> 
> Guys, you might want to create and connect a branch for this task because we will need to submit it anyway (if I am not mistaken in the docuementation directory) so it might as well be done like that.

Okay let's do it like that.

**Comment by tubamos** [comment]
@lukas-varga
@eloinoel

Updated the description of the task to include the formal requirements so that everything is in one place.
